disabled_rules: # rule identifiers to exclude from running
  - line_length
  - variable_name
  - force_cast
  - type_name
  - nesting
opt_in_rules:
  - missing-docs

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods